version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/chargex-telematics
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
    depends_on:
      - mongo
      - redis
    restart: always
    volumes:
      - ./data:/app/data

  api-docs:
    build: ./api-docs
    ports:
      - "3050:3050"
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - api-docs
    restart: always

volumes:
  mongo-data:
  redis-data:
